/* Données centralisées des projets
   Ajouter un projet ici le rend disponible partout :
   cartes index, filtres, pages détail */

const PROJECTS = [
    {
        slug:      'demain-peche',
        title:     'Demain — L\'éducation par la pêche',
        category:  ['iut', 'motion'],
        tags:      ['Documentaire', 'Interview', 'Drone'],
        summary:   'Un film documentaire réalisé autour de l\'éducation par la pêche et de la préservation des milieux aquatiques. Le projet s\'inscrit dans la série documentaire Demain et met en avant deux regards complémentaires : celui de Jean-François Jeandet, ancien président de l\'AAPPMA du Léguer, et celui de Yannick Line, guide et reporter de pêche.',
        label:     'IUT de Lannion',
        role:      'J\'ai participé à la préparation et à la production du documentaire avec mon groupe. Nous avons recherché un sujet, contacté les intervenants, préparé les questions, organisé les interviews et tourné les images nécessaires au montage final. Le projet demandait aussi un vrai travail de réflexion éditoriale : il fallait construire un angle clair autour de l\'éducation par la pêche, tout en montrant les enjeux liés à la préservation des rivières, au no kill et à l\'évolution des pratiques chez les jeunes.',
        process:   'Nous avons d\'abord défini le sujet du documentaire, puis identifié deux profils capables d\'apporter des points de vue différents. La première interview a été tournée chez Jean-François Jeandet, au bord d\'une rivière, afin d\'avoir un décor naturel directement lié au thème. La seconde a été réalisée avec Yannick Line, près du lac de Guerlédan, dans un cadre également cohérent avec l\'univers de la pêche. Pour enrichir le film, nous avons réalisé plusieurs plans de coupe : plans fixes de rivière, rochers, lac, bateau, ainsi que des plans au drone. Le tournage s\'est appuyé sur du matériel audiovisuel complet : Canon 90D, micros DJI, trépied, objectifs 50mm, 70-300mm et 18-135mm, drone DJI Mini 3 Pro et mixette H4 pour les ambiances sonores.',
        result:    'Le documentaire final met en lumière la pêche comme moyen d\'éducation, de transmission et de sensibilisation à l\'environnement. Les deux intervenants apportent des visions différentes mais complémentaires, notamment sur la pratique du no kill, la responsabilité des pêcheurs et l\'impact de nos habitudes sur les espèces vivant dans les cours d\'eau. Ce projet nous a permis de travailler dans des conditions réelles : recherche d\'intervenants, gestion des imprévus, interviews sur le terrain, captation image et son, puis sélection des informations les plus importantes pour un format court.',
        tools:     ['Canon 90D', 'Micros DJI', 'Drone DJI Mini 3 Pro', 'Mixette H4', 'Interview', 'Tournage documentaire', 'Storyboard', 'Plans de coupe'],
        thumb:     'pt-1',
        image:     'Images/PREVIEW/View_DEMMAIN.png',
        feat:      [
            { name: 'Ewen Lindor',      href: 'https://ewenlindor.fr' },
            { name: 'Ethan Lallauret',  href: 'https://www.ethanlallauret.fr' },
        ],
        video:     'https://www.youtube.com/embed/2GS1XvzpksQ?list=PLM8AYv9xW4JyLqnWTIopKbpchLx04NqOY',
        status:    'Réalisé',
        date:      '2025',
    },
    {
        slug:      'radiowave',
        title:     'RadioWave — Journal radio',
        category:  ['iut', 'communication'],
        tags:      ['Journalisme', 'Radio', 'Présentation'],
        summary:   'Ce projet consistait en la production d\'une émission d\'information en conditions proches du réel, reproduisant les étapes de fabrication d\'un journal radio, de la conférence de rédaction jusqu\'à l\'enregistrement final, en travaillant à la fois l\'écriture journalistique, l\'organisation d\'équipe et la prise de parole.',
        label:     'IUT de Lannion',
        role:      'J\'ai occupé un double rôle sur ce projet : rédacteur d\'un sujet avec mon binôme et présentateur de l\'émission avec une camarade. J\'ai participé à la rédaction des titres, des lancements, des transitions, des conclusions et des flashs d\'information. Ce rôle demandait d\'être clair, dynamique et précis, tout en respectant le conducteur et le timing de l\'émission. J\'ai aussi travaillé sur un duplex audio autour de la guerre en Iran, en adaptant les informations au format radio pour rendre le sujet plus fluide et compréhensible à l\'oral.',
        process:   'Le projet a commencé par une conférence de rédaction, avec des échanges, débats et choix éditoriaux pour construire le journal. Ensuite, nous avons recherché et hiérarchisé les informations, en sélectionnant des sources fiables et complémentaires. La phase d\'écriture a été importante : les textes ont été retravaillés en plusieurs versions, d\'abord explicatives, puis plus adaptées à l\'oral, avec des phrases plus courtes et un rythme plus radiophonique. Des répétitions ont ensuite permis de caler les prises de parole, les transitions et les lancements audio avant l\'enregistrement final.',
        result:    'L\'émission a été enregistrée dans le respect du timing, malgré quelques incompréhensions entre la régie et les présentateurs au moment des lancements audio. Ce projet m\'a permis de développer des compétences concrètes en rédaction radio, en prise de parole, en gestion du stress, en coordination d\'équipe et en rigueur journalistique. Cette expérience m\'a particulièrement marqué, notamment pour l\'adrénaline de la présentation en direct et la responsabilité liée au rôle de présentateur. Elle a aussi confirmé mon intérêt pour le monde de la presse, de la présentation et du travail en rédaction.',
        tools:     ['Écriture journalistique', 'Présentation radio', 'Conférence de rédaction', 'Duplex audio', 'Recherche d\'informations', 'Travail d\'équipe', 'Bemymedia'],
        thumb:     'pt-2',
        image:     'Images/PREVIEW/View_RW.png',
        feat:      [
            { name: 'Ethan Lallauret',  href: 'https://www.ethanlallauret.fr' },
            { name: 'Emma Texier',      href: 'https://www.emmatexier.fr/index.html' },
            { name: 'Ewen Lindor',      href: 'https://ewenlindor.fr' },
            { name: 'Roxane Omnes',     href: 'https://www.behance.net/gallery/247513745/Portfolio-communication' },
            { name: 'Vince Linise',     href: 'https://vincelinise.com' },
            { name: 'Rachel Le Saux',   href: 'https://www.linkedin.com/in/rachel-le-saux-20a75626b/' },
            { name: 'Valentin Samson',  href: 'https://valentinsamson.fr' },
            { name: 'Enzo Le Vourc\'h', href: 'https://enzolevourch.github.io' },
            { name: 'Juliette Goujon',  href: 'https://juliettegoujon.artstation.com' },
            { name: 'Timéo Devos',      href: 'https://www.linkedin.com/in/timéo-devos/' },
            { name: 'Martin Aballéa',   href: 'https://www.linkedin.com/in/martin-aballéa-b06596290/' },
        ],
        videos:    [
            { url: 'https://www.youtube.com/embed/ViqLSV_xTZs', label: 'Le journal radio' },
            { url: 'https://www.youtube.com/embed/KcFCA1V1R3M', label: 'Coulisses (réalisé par deux camarades)' },
        ],
        status:    'Réalisé',
        date:      '2025',
    },
    {
        slug:      'shift',
        title:     'Shift — Média automobile',
        category:  ['iut', 'communication', 'reseaux'],
        tags:      ['Média digital', 'Rédaction web', 'Instagram'],
        summary:   'Shift est un média en ligne consacré aux voitures dans les jeux vidéo. Le projet consistait à créer un magazine digital avec une identité, une ligne éditoriale, des articles et une stratégie Instagram, avec pour objectif de valoriser la culture automobile virtuelle auprès des gamers et passionnés d\'automobile.',
        label:     'IUT de Lannion',
        role:      'J\'ai participé à la création du média Shift, de son positionnement éditorial et de sa stratégie réseaux sociaux. Le média vise principalement les gamers passionnés de jeux de voitures, mais aussi les fans de culture automobile, de tuning, de simulation et de pop culture. J\'ai aussi rédigé un article sur Rocket League, avec l\'objectif de faire découvrir le jeu à un public large, en expliquant simplement son concept, ses modes de jeu et son importance dans la scène esport.',
        process:   'Nous avons commencé par un brainstorming autour des voitures dans les jeux vidéo : tuning, véhicules mythiques, jeux de course, simulation, open world et culture gaming. À partir de cette base, nous avons construit l\'identité du média avec un logo inspiré d\'un tracé de circuit, des couleurs vives et un ton à la fois convivial, passionné et sérieux. La ligne éditoriale repose sur plusieurs types de contenus : portraits de voitures iconiques, tests de jeux, interviews, classements et dossiers autour de l\'automobile virtuelle. Nous avons ensuite décliné cette identité sur un magazine en ligne et sur Instagram, avec une charte éditoriale et des posts pensés pour rediriger les internautes vers les articles.',
        result:    'Le projet aboutit à un média digital complet, avec un nom, une identité graphique, une cible, une ligne éditoriale, des articles et une stratégie de publication. Mon article sur Rocket League permet de présenter le jeu comme une référence culturelle du jeu vidéo automobile, en montrant son accessibilité, sa scène compétitive et son statut de jeu culte. La partie réseaux sociaux donne au projet une vraie logique de diffusion : Instagram sert à présenter le média, montrer des exemples d\'articles et créer une porte d\'entrée vers le magazine en ligne.',
        tools:     ['Écriture multimédia', 'Ligne éditoriale', 'Stratégie réseaux sociaux', 'Instagram', 'Magazine en ligne', 'Rédaction web', 'Identité de média'],
        thumb:     'pt-3',
        image:     'Images/PREVIEW/Logo_SHIFT.jpg',
        feat:      [
            { name: 'Kiéran Le Troadec', href: 'https://portfolio-kieran.vercel.app' },
        ],
        video:     'https://read.bookcreator.com/mF-YL8pWtAvYMLnms6ebwjBRIyOYa-oNpK0rA2ScFwU/PzKVluZJSkaFfFT2xB0oDg/yGAJwvRET0iX93jOoGSINA',
        links:     [
            { label: 'Instagram @shift.jv', href: 'https://www.instagram.com/shift.jv/' },
        ],
        status:    'Réalisé',
        date:      '2025',
    },
    {
        slug:      'mailsense',
        title:     'MailSense — Messagerie éco-responsable',
        category:  ['iut', 'ux-ui'],
        tags:      ['UX Design', 'Éco-conception', 'Figma'],
        summary:   'Un projet UX autour d\'une messagerie éco-responsable inspirée de Gmail. L\'objectif était d\'analyser le fonctionnement de Gmail, ses forces et ses limites, puis d\'imaginer une évolution de l\'email capable de rendre visible l\'impact environnemental des messages et des pièces jointes.',
        label:     'IUT de Lannion',
        role:      'J\'ai participé à l\'analyse UX de Gmail et à la conception d\'un concept de messagerie plus responsable. Le travail consistait à déconstruire l\'interface existante, identifier les fonctionnalités principales, repérer les points de friction et proposer de nouvelles fonctionnalités centrées sur la compréhension de l\'impact carbone. Avec mon binôme, nous avons aussi travaillé sur le positionnement du projet : transformer l\'email en un outil plus conscient, qui accompagne l\'utilisateur avant, pendant et après l\'envoi d\'un message.',
        process:   'Nous avons suivi une démarche inspirée du UX Design et du double diamant : analyse du fonctionnement de l\'email, déconstruction de Gmail, benchmark des services concurrents, identification des pain points, puis phase d\'idéation. L\'analyse a montré que Gmail est très complet, mais parfois complexe : les labels, catégories, filtres et options avancées peuvent créer une surcharge cognitive. Nous avons aussi identifié un manque important : l\'impact environnemental des emails et des pièces jointes n\'est jamais visible pour l\'utilisateur. À partir de ce constat, nous avons imaginé plusieurs fonctionnalités : analyse de l\'impact des pièces jointes, compression intelligente, conversion des fichiers en liens, tableau de bord écologique, suivi de l\'empreinte carbone, système de guidage et gamification.',
        result:    'Le projet aboutit à un concept de messagerie plus pédagogique et responsable. L\'interface ne se contente plus d\'envoyer des emails : elle aide l\'utilisateur à comprendre, optimiser et suivre l\'impact de ses actions numériques. Le parcours utilisateur montre une expérience fluide : l\'utilisateur ajoute une pièce jointe, visualise son impact, peut l\'optimiser, puis consulte les économies réalisées dans un tableau de bord. Cette approche transforme l\'email en véritable espace de décision, plus lisible et plus durable.',
        tools:     ['UX Design', 'Benchmark', 'Design thinking', 'User Journey Map', 'Figma', 'Analyse fonctionnelle', 'Éco-conception numérique'],
        thumb:     'pt-4',
        image:     'Images/PREVIEW/View_MAILSENSE.png',
        feat:      [
            { name: 'Ethan Lallauret', href: 'https://www.ethanlallauret.fr' },
        ],
        video:     'https://www.figma.com/embed?embed_host=share&url=' + encodeURIComponent('https://www.figma.com/proto/AjZ3eh4gg7lDRAUaqw3sM7/R4.03-GMAIL?node-id=7-307&viewport=271%2C310%2C0.05&t=6a9RKOJHXplGQx0D-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=7%3A307&page-id=0%3A1'),
        links:     [
            { label: 'Ouvrir le prototype Figma', href: 'https://www.figma.com/proto/AjZ3eh4gg7lDRAUaqw3sM7/R4.03-GMAIL?node-id=7-307&starting-point-node-id=7%3A307' },
        ],
        status:    'Réalisé',
        date:      '2025',
    },
    {
        slug:      'roz-tregor',
        title:     'Roz Trégor — App culturelle',
        category:  ['iut', 'ux-ui'],
        tags:      ['UX/UI', 'App Mobile', 'Figma'],
        summary:   'Une application mobile culturelle dédiée aux événements du Trégor. Le projet consiste à concevoir une application qui regroupe les spectacles, concerts et événements de plusieurs salles du territoire, comme Le Carré Magique, An Dour Meur, Le Sémaphore ou Le SKOPE.',
        label:     'IUT de Lannion',
        role:      'J\'ai participé à la recherche UX/UI, à l\'analyse des plateformes existantes et à la conception de l\'interface. Le travail a porté sur la création des wireframes, du design system, de la maquette et des parcours utilisateurs.',
        process:   'Nous avons d\'abord étudié les offres culturelles du Trégor, puis réalisé un benchmark de plateformes comme Ticketmaster, Dice, HelloAsso et Les Scènes du Golfe. Ces recherches nous ont permis de définir une application mobile simple, moderne, accessible et personnalisée.',
        result:    'La maquette finale propose une expérience mobile permettant de découvrir des événements, consulter les détails d\'un spectacle et réserver des places. L\'application intègre aussi des recommandations personnalisées selon les goûts de l\'utilisateur.',
        tools:     ['Figma', 'Wireframe', 'Design system', 'UX/UI', 'Benchmark'],
        thumb:     'pt-1',
        image:     'Images/PREVIEW/View_ROZ.png',
        feat:      [
            { name: 'Alban Desbordes', href: 'https://www.linkedin.com/in/alban-desbordes/' },
        ],
        video:     'https://www.figma.com/embed?embed_host=share&url=' + encodeURIComponent('https://www.figma.com/proto/ngaseYepCZVQUHlTGz7yc2/ROZ-Culture?node-id=33-569&viewport=116%2C490%2C0.14&t=yvJhnRQ6DhFR1Gm7-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=33%3A569&show-proto-sidebar=1&page-id=0%3A1'),
        links:     [
            { label: 'Ouvrir le prototype Figma', href: 'https://www.figma.com/proto/ngaseYepCZVQUHlTGz7yc2/ROZ-Culture?node-id=33-569&starting-point-node-id=33%3A569' },
        ],
        status:    'Réalisé',
        date:      '2025',
    },
    {
        slug:      '12-coups-mmi',
        title:     'Les 12 Coups de MMI',
        category:  ['iut', 'ux-ui'],
        tags:      ['VR', 'Unity', 'UX', 'Gestion de projet'],
        summary:   'Un dispositif interactif immersif conçu pour les Journées Portes Ouvertes 2026 de l\'IUT de Lannion. Le projet a pour objectif de faire découvrir le BUT MMI aux lycéens et à leurs familles à travers une expérience courte, ludique et immersive en réalité virtuelle, pour rendre la formation plus concrète en montrant la diversité des domaines MMI sans passer par un discours trop long ou trop scolaire.',
        label:     'IUT de Lannion',
        role:      'J\'ai travaillé en binôme sur la conception globale du dispositif, de l\'idée de départ jusqu\'au cahier des charges final. Nous avons défini le concept, les objectifs, les contraintes d\'usage, les besoins matériels et la méthodologie du projet. J\'ai aussi participé à la réflexion UX autour du parcours utilisateur, de la simplicité des interactions et de la manière de rendre l\'expérience compréhensible pour un public novice en réalité virtuelle. Le projet demandait aussi une réflexion sur la mise en scène du stand : le casque Meta Quest 3, la retransmission vidéo pour les accompagnants, la zone de jeu sécurisée et le matériel permettant une installation rapide et réutilisable.',
        process:   'Nous sommes partis d\'un constat simple : lors des JPO, beaucoup de lycéens découvrent la formation MMI sans toujours comprendre clairement ce que signifie "multimédia". Le dispositif devait donc leur permettre de comprendre rapidement les grands pôles de la formation, tout en levant la peur de poser des questions ou d\'être jugé. Le concept a ensuite été pensé sous forme de jeu en réalité virtuelle développé sur Unity et utilisable de manière autonome sur Meta Quest 3. L\'expérience devait durer environ 4 à 6 minutes, être facile à prendre en main et permettre un enchaînement fluide des visiteurs pendant la journée. Les interactions ont donc été volontairement limitées à des actions simples comme sélectionner, attraper ou déposer des éléments. Le projet a aussi intégré une démarche d\'évaluation avec un questionnaire utilisateur et une grille d\'observation.',
        result:    'Le livrable final est un cahier des charges complet pour un dispositif VR réutilisable lors des Journées Portes Ouvertes, salons ou présentations pédagogiques. Il définit le contexte, les objectifs, le principe de l\'expérience, les moyens techniques, les contraintes, les acteurs du projet, les livrables attendus et la méthode d\'évaluation. Le dispositif final est pensé pour être installé rapidement, fonctionner sans ordinateur externe et être compréhensible aussi bien par l\'utilisateur dans le casque que par les parents ou encadrants grâce à une retransmission vidéo.',
        tools:     ['Unity', 'Meta Quest 3', 'Réalité virtuelle', 'UX', 'Cahier des charges', 'Questionnaire utilisateur', 'Grille d\'observation', 'Gestion de projet'],
        thumb:     'pt-2',
        image:     'Images/PREVIEW/View_12COUPSpng.png',
        feat:      [
            { name: 'Ethan Lallauret', href: 'https://www.ethanlallauret.fr' },
        ],
        status:    'Réalisé',
        date:      '2026',
    },
];

/* Catégories disponibles pour les filtres */
const PROJECT_CATEGORIES = [
    { id: 'all',           label: 'Tous' },
    { id: 'iut',           label: 'IUT de Lannion' },
    { id: 'ux-ui',         label: 'UX/UI' },
    { id: 'branding',      label: 'Branding' },
    { id: 'communication', label: 'Communication' },
    { id: 'reseaux',       label: 'Réseaux sociaux' },
    { id: 'motion',        label: 'Motion / Vidéo' },
    { id: 'web',           label: 'Web' },
];
